manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: myfork
      url-base: https://github.com/simply_miquel

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-nice-oled
      remote: myfork
      revision: main
      path: modules/zmk-nice-oled

  self:
    path: config
